# Generated by Django 5.0.2 on 2024-02-24 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth', models.CharField(max_length=50)),
                ('shoes', models.CharField(max_length=50)),
                ('accessories', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name_company'],
            },
        ),
        migrations.CreateModel(
            name='Reserv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reserved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summer', models.CharField(max_length=50)),
                ('winter', models.CharField(max_length=50)),
                ('spring', models.CharField(max_length=50)),
                ('autumn', models.CharField(max_length=50)),
                ('demi_season', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SizeCloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizeOne', models.IntegerField(max_length=10)),
                ('sizeTwo', models.IntegerField(max_length=10)),
                ('sizeThree', models.IntegerField(max_length=10)),
                ('sizeFour', models.IntegerField(max_length=10)),
                ('sizeFive', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SizeShoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizeOne', models.IntegerField(max_length=10)),
                ('sizeTwo', models.IntegerField(max_length=10)),
                ('sizeThree', models.IntegerField(max_length=10)),
                ('sizeFour', models.IntegerField(max_length=10)),
                ('sizeFive', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_prod', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('product_composition', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('product_count', models.IntegerField(max_length=200)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.category')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
                ('reserv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.reserv')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.season')),
                ('size_cloth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.sizecloth')),
                ('size_shoes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.sizeshoes')),
            ],
            options={
                'ordering': ['name_prod'],
            },
        ),
    ]
